- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop existing containers
      shell: |
        CONTAINERS=$(docker ps -q)
        if [ -n "$CONTAINERS" ]; then
          docker stop $CONTAINERS
        else
          echo "No containers to stop."
        fi
      ignore_errors: yes

    - name: Delete all containers
      shell: |
        CONTAINERS=$(docker ps -a -q)
        if [ -n "$CONTAINERS" ]; then
          docker rm $CONTAINERS
        else
          echo "No containers to remove."
        fi
      ignore_errors: yes

    - name: Deploy Docker Container
      docker_container:
        name: insurance-mentor
        image: advit2012/insureme:1
        state: started
        ports:
          - "8085:8081"
